### ISSUE TITLE
Reduce external dependencies

### ISSUE THREAD

**Issue by f1ana** [uvasoftware/scanii-dotnet#17]
I've noticed that this library has a dependency on Serilog, as well as RestSharp.
My opinion is that libraries should not require the user to rely on a specific logger implementation.  Perhaps replacing Serilog with something more generic, like `Microsoft.Extensions.Logging.Abstractions` would be a better alternative.  This would allow developers to implement without having possible competing logging platforms.
Also, is there anything that requires the usage of RestSharp here?

**Comment by rferreira** [comment]
@f1ana I'm good with replacing serilog with a facade and Microsoft.Extensions.Logging seems like a sensible one. Now RestSharp that is used quite extensively as our underlying http client (https://github.com/uvasoftware/scanii-dotnet/blob/master/UvaSoftware.Scanii/ScaniiClient.cs#L52) so I'm less inclined to consider replacing it. 

In any case, PRs are always welcomed.

**Comment by rferreira** [comment]
addressed in latest release https://github.com/uvasoftware/scanii-dotnet/releases/tag/v4.0.2
